import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SmokeyCursor from "@/components/lightswind/smokey-cursor";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hemant's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/javascript.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white relative overflow-x-hidden`}
      >
        {/* Cosmic Background Planet/Ring Effect */}
        <div className="cosmic-planet-overlay" />

        {/* 📄 App content */}
        <div className="relative z-10">{children}</div>

        {/* 🖱️ Foreground cursor effect */}
        <SmokeyCursor />
      </body>
    </html>
  );
}
