import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import MouseTracker from "@/components/MouseTracker/page";
// import ParticleOrbitEffect from "@/components/lightswind/particle-orbit-effect";
import SmokeyCursor from "@/components/lightswind/smokey-cursor";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hemant's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white relative overflow-x-hidden`}
      >
        {/* 📄 App content */}
        <div className="relative z-10">{children}</div>

        {/* 🖱️ Foreground cursor effect */}
        <SmokeyCursor />
      </body>
    </html>
  );
}
